Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
a = int(input("enter the number :"))
b = int(input("enter the second number : "))
try:
    c =a/b
except:
    print("Airthmetic Error")
else:
    print("The  Result is :",c)

enter the number5
enter the second number0
Airthmetic Error


In [ ]:
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [25]:
subjects=["Americans ","Indians "]
verbs=["play ","watch "]
objects=["Baseball","Cricket"]
result = [x+y+z+"." for x in subjects for y in verbs for z in objects]
#convert the list to str and print it according to desired output
for x in result:
    print(x)



Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [26]:
import numpy as np
def convertUserIpToArray(userInput):
    myCustomList = []
    Input = userInput.split(",")
    for element in Input:
        myCustomList.append(int(element))
    arr = np.array(myCustomList)
    return arr
def generateVanderMatrix(ipList,noOpCol,increasing):
        if(increasing):
          
            Result_op = np.array([x**y for x in ipList for y in range(noOpCol)]).reshape(ipList.size,noOpCol)
        else:
             Result_op = np.array([x**(noOpCol-1-y) for x in ipList for y in range(noOpCol)]).reshape(ipList.size,noOpCol)
        return Result_op

userList = convertUserIpToArray(input("Enter the  list of number :"))
opCol = int(input("Enter the number of coutput columns needed : "))
increaseOrder = generateVanderMatrix(userList,opCol,True)
decreaseOrder = generateVanderMatrix(userList,opCol,False)
print("\nOutput matrix in Increasing order\n",increaseOrder)
print("\nOutput matrix in Decreasing order\n",decreaseOrder)

Enter the  list of number :1,2,3,4
Enter the number of coutput columns needed : 3

Output matrix in Increasing order
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]

Output matrix in Decreasing order
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
